Servidores3/urls.py
# nome_do_projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_app.urls')),
    path('admin/', admin.site.urls),
    path('servidores/', include('servidores_app.urls')),
    path('programas/', include('escolas_conectadas_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dispositivos/', include('dispositivos_app.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from .views import  home

urlpatterns = [
    path('', home, name='home'),
]

dispositivos_app/models.py
from django.db import models

# Escolhas para o tipo de dispositivo
TIPO_CHOICES = [
    ('chromebook', 'Chromebook'),
    ('notebook', 'Notebook')
]

# Escolhas para o status do dispositivo
STATUS_CHOICES = [
    ('estoque', 'Estoque'),
    ('manutencao', 'Manutenção'),
    ('com_servidor', 'Com servidor'),
    ('inativo', 'Inativo')
]

class Dispositivo(models.Model):
    Status = models.CharField(max_length=255, choices=STATUS_CHOICES, blank=True)
    tipo = models.CharField(max_length=255, choices=TIPO_CHOICES, blank=True)
    nome_servidor = models.CharField(max_length=100, blank=True)
    # numero_de_serie = models.CharField(max_length=50, blank=True)
    CPF = models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        return self.numero_de_serie

class Documento(models.Model):
    dispositivo = models.ForeignKey(Dispositivo, on_delete=models.CASCADE, related_name='documentos')
    arquivo = models.FileField(upload_to='documents/')
    
    def __str__(self):
        return self.arquivo.name

escolas_conectadas_app/models.py
from django.db import models
from django.core.validators import RegexValidator

class Escolas(models.Model):
    inep = models.CharField(max_length=8, validators=[RegexValidator(r'^\d{8}$', 'O INEP deve ter exatamente 8 dígitos.')])
    nome = models.CharField(max_length = 100)
    status = models.CharField(max_length = 40,blank=True)
    longitude = models.CharField(max_length = 20,blank=True)
    latitude = models.CharField(max_length = 20,blank=True)
    endereco = models.CharField(max_length = 50,blank=True)

servidores_app/models.py
# seu_app/models.py

import uuid
from django.db import models
from cpf_field.models import CPFField
from django.core.exceptions import ValidationError
import os
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.contrib.auth.models import Group

VINCULO_CHOICES = [
        ('contratado', 'Contratado'),
        ('efetivo', 'Efetivo'),
        ('comissionado', 'Comissionado'),
        ('outro', 'Outro'),]

class Usuario(models.Model):
    nome = models.CharField(max_length=100)
    cpf = CPFField('cpf', unique=True, null=True, error_messages={'unique': 'Já existe um usuário com este CPF. Por favor, escolha outro.'})
    email = models.EmailField(max_length=50, unique=True, null=True, error_messages={'unique': 'Já existe um usuário com este e-mail. Por favor, escolha outro.'})
    telefone = models.CharField(max_length=11)
    instituicao = models.CharField(max_length=50, null=True)
    vinculo = models.CharField(max_length=30, null=True, choices=VINCULO_CHOICES)
    cargo = models.CharField(max_length=30, null=True)
    ch = models.PositiveIntegerField(null=True,default=20)  # Alterado para IntegerField se ch representar carga horária
    rg = models.CharField(max_length=8, null=True)
    org_expedidor = models.CharField(max_length=10, null=True)
    endereco = models.CharField(max_length=100, null=True)
    escolaridade = models.CharField(max_length=50, null=True)
    imagem_perfil = models.ImageField(upload_to='imagens_perfil/', blank=True, null=True)



    def clean(self):
        super().clean()

        # Validar se o campo telefone tem exatamente 11 caracteres numéricos
        if self.telefone and (not self.telefone.isdigit() or len(self.telefone) != 11):
            raise ValidationError('O número de telefone deve conter exatamente 11 dígitos numéricos.')
        
        # Validar se o campo rg tem exatamente 8 caracteres numéricos
        if self.rg and (not self.rg.isdigit() or len(self.rg) != 8):
            raise ValidationError('O número do rg deve conter exatamente 8 dígitos numéricos.')


class CustomUsuario(Usuario):
    pass
    def clean(self):
        super().clean()
        print("Entrou no método clean")  # Adicione esta linha para debug

        # Exemplo de validação personalizada para o campo 'email'
        if CustomUsuario.objects.exclude(pk=self.pk).filter(email=self.email).exists():
            raise ValidationError('Já existe um usuário com este e-mail. Por favor, escolha outro.')

        # Exemplo de validação personalizada para o campo 'cpf'
        if CustomUsuario.objects.exclude(pk=self.pk).filter(cpf=self.cpf).exists():
            raise ValidationError('Já existe um usuário com este CPF. Por favor, escolha outro.')

@receiver(post_delete, sender=Usuario)
def delete_usuario_image(sender, instance, **kwargs):
    # exclua a imagem quando o usuário for excluído
    if instance.imagem_perfil:
        if os.path.isfile(instance.imagem_perfil.path):
            os.remove(instance.imagem_perfil.path)

templates/adicionar_documento.html
<!DOCTYPE html>
<html lang="en">
    <div style="margin: 20 auto;"> <!-- Adiciona margens laterais e define a largura máxima -->
        <div style="position: relative;">
            <h1 style="text-align: center; font-weight: bold; color: white; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 1; font-size: 24px;">ADICIONAR DOCUMENTO</h1>
            <div style="background-color: #023059; height: 50px;"></div>
        </div>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Documento</title>
    <!-- Adicione os links para os arquivos CSS do Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Estilos para centralizar o conteúdo na parte superior */
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: flex-start;
            min-height: 100vh;
            padding: 20px;
        }

        .content {
            max-width: 600px;
            width: 100%;
        }

        .button-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="content">
            <form method="post" enctype="multipart/form-data" class="mt-3">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-container">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Adicione os scripts do Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/cadastrar_usuarios.html
{% extends 'blank.html' %}
{% block central %}

<div style="position: relative;">
    <h1 style="text-align: center; font-weight: bold; color: white; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 1; font-size: 24px;">CADASTRAR SERVIDORES</h1>
    <div style="background-color: #023059; height: 50px;"></div>
</div>


<div class="container-fluid">

    <!-- Page Heading -->
   
    <style>
        .container-fluid {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            width: 100%;
            max-width: 2200px; /* Defina o tamanho máximo conforme necessário */
        }
    </style>

    <div class="container-fluid">
        <!-- Page Heading -->
        
        <form method="post" enctype="multipart/form-data" class="text-center" style="margin-top: 0px;">
            {% csrf_token %}
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_nome">Nome:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_nome" name="nome" placeholder="Nome Completo...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_rg">RG:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_rg" name="rg" placeholder="Digite o RG...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_org_expedidor">Org expedidor:</label> {% endcomment %}
                    <select class="form-control" id="id_org_expedidor" name="org_expedidor">
                        <option value="">Selecione o org expedidor</option>
                        <option value="SSP/AL">SSP/AL</option>
                        <option value="SSPO">SSPO</option>
                        <option value="outro">Outro</option>
                    </select>
                </div>
            </div>
    
            <div class="form-row">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_cpf">CPF:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_cpf" name="cpf" placeholder="Insira o CPF...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_email">Email:</label> {% endcomment %}
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Ex.:semecgirau@gmail.com">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_telefone">Telefone:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_telefone" name="telefone" placeholder="Telefone para contato...">
                </div>
            </div>
    
            <div class="form-row">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_cargo">Cargo:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_cargo" name="cargo" placeholder="Digite o cargo...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_vinculo">Vínculo:</label> {% endcomment %}
                    <select class="form-control" id="id_vinculo" name="vinculo">
                        <option value="">Selecione o vínculo</option>
                        <option value="Efetivo">Efetivo</option>
                        <option value="Temporário">Temporário</option>
                        <option value="Comissionado">Comissionado</option>
                        <option value="Outro">Outro</option>
                    </select>
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_ch">CH:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_ch" name="ch" placeholder="Carga Horária (Ex.: 20h)">
                </div>
            </div>
    
            <div class="form-row">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_instituicao">Instituição:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_instituicao" name="instituicao" placeholder="Digite a instituição...">
                </div>
                <div class="
    
                form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                {% comment %} <label for="id_escolaridade">Escolaridade:</label> {% endcomment %}
                <select class="form-control" id="id_escolaridade" name="escolaridade">
                    <option value="">Selecione a escolaridade</option>
                    <option value="Ens. Fundamental">Ens. Fundamental</option>
                    <option value="Ens. Médio">Ens. Médio</option>
                    <option value="Ens. Médio Incompleto">Ens. Médio Incompleto</option>
                    <option value="Superior">Superior</option>
                    <option value="Superior Incompleto">Superior Incompleto</option>
                    <option value="Mestre">Mestre</option>
                    <option value="Doutor">Doutor(a)</option>
                </select>
            </div>
            
            <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                {% comment %} <label for="id_endereco">Endereço:</label> {% endcomment %}
                <input type="text" class="form-control" id="id_endereco" name="endereco" placeholder="Digite o endereço...">
            </div>
        </div>
        <div class="form-row justify-content-start align-items-center" style="height: -200vh;">
            <div class="form-group col-md-4 text-center" style="border: 0px solid #ccc; padding: 0px;">
                <input type="file" class="form-control" id="id_imagem_perfil" name="imagem_perfil" style="margin-bottom: 5px;" onchange="previewImage(event)">
                <label for="id_imagem_perfil" style="margin-bottom: 10px; text-align: left;">Imagem perfil:</label>
                <div id="previewContainer" style="height: 150px; overflow: hidden; display: flex; justify-content: align-items:">
                    <img id="preview" src="#" alt="Prévia da imagem" style="display: none; max-width: 30%; height: auto; margin-top: 10px;">
                </div>
            </div>
        </div>
        
        
        <script>
            function previewImage(event) {
                var reader = new FileReader();
                reader.onload = function() {
                    var preview = document.getElementById('preview');
                    preview.src = reader.result;
                    preview.style.display = 'block';
                }
                reader.readAsDataURL(event.target.files[0]);
            }
        </script>                 
        
        
        <button type="submit" class="btn btn-primary"style="background-color: #0E7331; width: 200px; margin-top: -200px;">CADASTRAR</button>
      
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </form>
    
    </div>
{% endblock %}

templates/editar_dispositivos.html
{% extends 'blank.html' %}
{% block central %}
<div style="margin: 0 auto;"> <!-- Adiciona margens laterais e define a largura máxima -->
    <div style="position: relative;">
        <h1 style="text-align: center; font-weight: bold; color: white; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 1; font-size: 24px;">EDITAR DISPOSITIVOS</h1>
        <div style="background-color: #023059; height: 50px;"></div>
    </div>

    <div class="container-fluid">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data" id="editForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_tipo">Tipo:</label>
                        <input type="text" name="tipo" id="id_tipo" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_nome_servidor">Nome do Servidor:</label>
                        <input type="text" name="nome_servidor" id="id_nome_servidor" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_numero_de_serie">Número de Série:</label>
                        <input type="text" name="numero_de_serie" id="id_numero_de_serie" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_status">Status:</label>
                        <input type="text" name="status" id="id_status" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_documento">Documento:</label>
                        <input type="file" name="documento" id="id_documento" class="form-control-file">
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary" id="submitButton">Salvar</button>
                    </div>
                </form>
                <div id="successMessage" style="display: none; text-align: center; color: green;">Alterações feitas com sucesso!</div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById("editForm").addEventListener("submit", function(event) {
        event.preventDefault(); // Impede o envio do formulário padrão

        // Mostra a mensagem de sucesso por 3 segundos
        document.getElementById("successMessage").style.display = "block";
        setTimeout(function() {
            document.getElementById("successMessage").style.display = "none";
            document.getElementById("editForm").submit(); // Envie o formulário após exibir a mensagem
        }, 3000); // 3 segundos
    });
</script>

{% endblock %}

templates/editar_usuario.html
{% extends 'blank.html' %}
{% block central %}

<div style="margin: 0 auto; max-width: 1200px;"> <!-- Adiciona margens laterais e define a largura máxima -->
    <div style="position: relative;">
        <h1 style="text-align: center; font-weight: bold; color: white; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 1; font-size: 24px;">EDITAR SERVIDORES</h1>
        <div style="background-color: #023059; height: 50px;"></div>
    </div>

        {% csrf_token %}
        <!-- Exibir a imagem atual -->
        {% if form.instance.imagem_perfil %}
        <img src="{{ form.instance.imagem_perfil.url }}" alt="Imagem Atual" width="100" height="120">
        {% endif %}
        
        <!-- Adicionar campo de upload de imagem -->
        <label for="id_imagem_perfil">Editar Imagem:</label>
        {{ form.imagem_perfil }}

        <form method="post" enctype="multipart/form-data" class="text-center" style="margin-top: 0px;">
            {% csrf_token %}
            <div class="form-row justify-content-center">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_nome">Nome:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_nome" name="nome" placeholder="Nome Completo...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_rg">RG:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_rg" name="rg" placeholder="Digite o RG...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_org_expedidor">Org expedidor:</label> {% endcomment %}
                    <select class="form-control" id="id_org_expedidor" name="org_expedidor">
                        <option value="">Selecione o org expedidor</option>
                        <option value="SSP/AL">SSP/AL</option>
                        <option value="SSPO">SSPO</option>
                        <option value="outro">Outro</option>
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_cpf">CPF:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_cpf" name="cpf" placeholder="Insira o CPF...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_email">Email:</label> {% endcomment %}
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Ex.:semecgirau@gmail.com">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_telefone">Telefone:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_telefone" name="telefone" placeholder="Telefone para contato...">
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_cargo">Cargo:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_cargo" name="cargo" placeholder="Digite o cargo...">
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_vinculo">Vínculo:</label> {% endcomment %}
                    <select class="form-control" id="id_vinculo" name="vinculo">
                        <option value="">Selecione o vínculo</option>
                        <option value="Efetivo">Efetivo</option>
                        <option value="Temporário">Temporário</option>
                        <option value="Comissionado">Comissionado</option>
                        <option value="Outro">Outro</option>
                    </select>
                </div>
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_ch">CH:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_ch" name="ch" placeholder="Carga Horária (Ex.: 20h)">
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                    {% comment %} <label for="id_instituicao">Instituição:</label> {% endcomment %}
                    <input type="text" class="form-control" id="id_instituicao" name="instituicao" placeholder="Digite a instituição...">
                </div>
                <div class="

                form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                {% comment %} <label for="id_escolaridade">Escolaridade:</label> {% endcomment %}
                <select class="form-control" id="id_escolaridade" name="escolaridade">
                    <option value="">Selecione a escolaridade</option>
                    <option value="Ens. Fundamental">Ens. Fundamental</option>
                    <option value="Ens. Médio">Ens. Médio</option>
                    <option value="Ens. Médio Incompleto">Ens. Médio Incompleto</option>
                    <option value="Superior">Superior</option>
                    <option value="Superior Incompleto">Superior Incompleto</option>
                    <option value="Mestre">Mestre</option>
                    <option value="Doutor">Doutor(a)</option>
                </select>
            </div>
            
            <div class="form-group col-md-4" style="border: 1px solid #ccc; padding: 5px;">
                {% comment %} <label for="id_endereco">Endereço:</label> {% endcomment %}
                <input type="text" class="form-control" id="id_endereco" name="endereco" placeholder="Digite o endereço...">
            </div>

            <button type="submit" class="btn btn-primary" style="background-color: #0E7331; width: 200px; margin: 80px auto 0;">SALVAR ALTERAÇÕES</button>
            <div id="successMessage" class="alert alert-success alert-dismissible fade mt-3" role="alert" style="display: none;">
                Alterações feitas com sucesso!
                <button type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <script>
                document.getElementById("saveButton").addEventListener("click", function() {
                    // Exibir a mensagem de sucesso
                    document.getElementById("successMessage").style.display = "block";
            
                    // Fechar a mensagem após 5 segundos
                    setTimeout(function() {
                        document.getElementById("successMessage").style.display = "none";
                    }, 5000);
                });
            </script>
    </form>

    {% if messages %}
    <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

{% endif %}

{% endblock %}

templates/inicio.html
{% extends 'blank.html' %}
{% block central%}
{% endblock%}

templates/medidor.html
{% extends 'blank.html' %}


{% block central %}
<div style="margin-top: 20px;"> <!-- Adiciona um espaço de 20 pixels no topo -->
    <div style="position: relative;">
        <h1 style="text-align: center; font-weight: bold; color: white; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 1; font-size: 24px;">LISTA DE ESCOLAS</h1>
        <div style="background-color: #023059; height: 50px;"></div>
    </div>
    
    <hr>

    <form action="" method="GET" style="margin: 20px 0;">
        <input type="text" name="nome" value="{{ request.GET.nome }}" autocomplete="off"
            placeholder="Nome ou parte dele..." style="margin-left: 130px;">
        <button type="submit" class="btn btn-success" style= "background-color: #0E7331; color: white;">Buscar</button>
        <a href="{% url 'programas' %}" class="btn btn-light" style="margin-left: 10px;background-color: #F2E313; color: black;">Limpar</a>
        <button type="button" id="btn-verificar" class="btn btn-primary float-right" style="margin-right: 130px; background-color: #023059; color: white;">Mapa Escolas</button>

    </form>
    
    
    
    <script>
        // Verifica se a URL contém '?mapa=true' ao carregar a página
        window.onload = function() {
            var url = window.location.href;
            if (url.indexOf('mapa=true') !== -1) {
                // Remove '?mapa=true' da URL
                var newUrl = url.replace('?mapa=true', '');
                // Atualiza a URL sem '?mapa=true'
                history.replaceState(null, null, newUrl);
                // Recarrega a página
                location.reload();
            }
        };
    
        document.getElementById("btn-verificar").addEventListener("click", function (event) {
            event.preventDefault(); // Evita o comportamento padrão de enviar o formulário
            var url = window.location.href; // Obtém a URL atual
    
            // Adiciona "?mapa=true" à URL apenas se já não estiver presente
            if (url.indexOf('mapa=true') === -1) {
                url += (url.indexOf('?') !== -1 ? '&' : '?') + 'mapa=true';
            }
    
            // Redireciona para a URL atualizada
            window.location.href = url;

            // Remove "?mapa=true" da URL após o redirecionamento
            var novaURL = window.location.href.replace('?mapa=true', '');
            history.replaceState(null, null, novaURL);
        });
    </script>

    <hr>
    <div style="display: flex; justify-content: center;">
    <table border="1">
        <thead align="center">
            <tr style="text-align: center;">
                <th>INEP</th>
                <th>NOME DA ESCOLA</th>
                <th>STATUS</th>
            </tr>
            
            
        </thead>
        <tbody>
            {% for escola in escolas %}
            <tr>
                <td>{{ escola.inep }}</td>
                <td>{{ escola.nome }}</td>
                <td>{{ escola.status }}</td>
                <td>{{ escola.longitude }}</td>
                <td>{{ escola.latitude }}</td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
            
            <!-- Modal de cópia -->
            <div id="modal-copia" class="modal">
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <p id="valor-inep-copiado"></p>
                    <button id="btn-copiar">Copiar</button>
                </div>
            </div>
        </tbody>
    </table>
</div>
</div>
{% endblock %}